spring:
  application:
    name: shippingservice
  cloud:
      config:
        uri: http://localhost:8090
management:
        security:
          enabled: false
name: Shipping Service version 1.0
server:
  port: 21912